default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: ror-auth0-api_v4_development

test:
  <<: *default
  database: ror-auth0-api_v4_test

production:
  <<: *default
  database: ror-auth0-api_v4_production
  username: ror-auth0-api_v4
  password: <%= ENV['ROR-AUTH0-API_V4_DATABASE_PASSWORD'] %>
