development:
  api_client_id: <%= ENV["API_CLIENT_ID"] %>
  api_client_secret: <%= ENV["API_CLIENT_SECRET"] %>
  oauth_client_id: <%= ENV["OAUTH_CLIENT_ID"] %>
  oauth_client_secret: <%= ENV["OAUTH_CLIENT_SECRET"] %>
  oauth_domain: <%= ENV["OAUTH_DOMAIN"] %>

test:
  api_client_id: <%= ENV["API_CLIENT_ID"] %>
  api_client_secret: <%= ENV["API_CLIENT_SECRET"] %>
  oauth_client_id: <%= ENV["OAUTH_CLIENT_ID"] %>
  oauth_client_secret: <%= ENV["OAUTH_CLIENT_SECRET"] %>
  oauth_domain: <%= ENV["OAUTH_DOMAIN"] %>

production:
  api_client_id: <%= ENV["API_CLIENT_ID"] %>
  api_client_secret: <%= ENV["API_CLIENT_SECRET"] %>
  oauth_client_id: <%= ENV["OAUTH_CLIENT_ID"] %>
  oauth_client_secret: <%= ENV["OAUTH_CLIENT_SECRET"] %>
  oauth_domain: <%= ENV["OAUTH_DOMAIN"] %>